# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWSPlFmB3CtO6vOohF8FCqQbDIKjHP6i
"""

!pip install streamlit

import streamlit as st
from calculator import show_calculator
from bmi_calculator import show_bmi
from area_calculator import show_area

st.set_page_config(page_title="Week7 Streamlit Activities", layout="centered")

st.title("Week 7 — Streamlit Workshop")
st.write("Sidebar se app choose karein:")

app = st.sidebar.selectbox("Choose app", ["Calculator", "BMI Calculator", "Area Calculator"])
st.sidebar.markdown("---")
st.sidebar.write("Made for: Workshop — Week 7")

if app == "Calculator":
    show_calculator()
elif app == "BMI Calculator":
    show_bmi()
elif app == "Area Calculator":
    show_area()